namespace SocialSiteAPI.Models
{
    public class Value
    {
        public int Id { get; set; } // as a convention in sqLite Id is used as a primary key and is autogenerated
        public string Name { get; set; }
    }
}
